2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] MongoDB starting : pid=9558 port=47018 dbpath=/data/shard1/rs1 64-bit host=kris-ThinkPad-X1-Carbon-5th
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] db version v3.4.10
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] modules: none
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] build environment:
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten]     distmod: ubuntu1604
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] options: { net: { port: 47018 }, processManagement: { fork: true }, replication: { replSet: "s1" }, sharding: { clusterRole: "shardsvr" }, storage: { dbPath: "/data/shard1/rs1" }, systemLog: { destination: "file", path: "s1-r1.log" } }
2017-12-03T21:00:45.970+0900 I STORAGE  [initandlisten] 
2017-12-03T21:00:45.970+0900 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-12-03T21:00:45.970+0900 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-12-03T21:00:45.970+0900 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7269M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-12-03T21:00:46.050+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.052+0900 W SHARDING [initandlisten] Started with --shardsvr, but no shardIdentity document was found on disk in admin.system.version. This most likely means this server has not yet been added to a sharded cluster.
2017-12-03T21:00:46.079+0900 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/shard1/rs1/diagnostic.data'
2017-12-03T21:00:46.107+0900 I REPL     [initandlisten] Did not find local voted for document at startup.
2017-12-03T21:00:46.107+0900 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2017-12-03T21:00:46.108+0900 I NETWORK  [thread1] waiting for connections on port 47018
2017-12-03T21:00:51.353+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43686 #1 (1 connection now open)
2017-12-03T21:00:51.354+0900 I -        [conn1] end connection 127.0.0.1:43686 (1 connection now open)
2017-12-03T21:00:51.354+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43690 #2 (1 connection now open)
2017-12-03T21:00:51.354+0900 I NETWORK  [conn2] received client metadata from 127.0.0.1:43690 conn2: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:51.355+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47017
2017-12-03T21:00:51.356+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47017, took 1ms (1 connections now open to localhost:47017)
2017-12-03T21:00:53.357+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43704 #3 (2 connections now open)
2017-12-03T21:00:53.357+0900 I -        [conn3] end connection 127.0.0.1:43704 (2 connections now open)
2017-12-03T21:00:53.402+0900 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-12-03T21:00:53.473+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43708 #4 (2 connections now open)
2017-12-03T21:00:53.473+0900 I NETWORK  [conn4] received client metadata from 127.0.0.1:43708 conn4: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:53.474+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47019
2017-12-03T21:00:53.476+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47019, took 1ms (1 connections now open to localhost:47019)
2017-12-03T21:00:53.478+0900 I REPL     [replication-0] Starting initial sync (attempt 1 of 10)
2017-12-03T21:00:53.478+0900 I REPL     [ReplicationExecutor] New replica set config in use: { _id: "s1", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "localhost:47017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "localhost:47018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "localhost:47019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a23e7737da32b8ce5ce759f') } }
2017-12-03T21:00:53.478+0900 I REPL     [ReplicationExecutor] This node is localhost:47018 in the config
2017-12-03T21:00:53.478+0900 I REPL     [ReplicationExecutor] transition to STARTUP2
2017-12-03T21:00:53.479+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state SECONDARY
2017-12-03T21:00:53.479+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state STARTUP2
2017-12-03T21:00:53.515+0900 I REPL     [replication-0] sync source candidate: localhost:47017
2017-12-03T21:00:53.515+0900 I STORAGE  [replication-0] dropAllDatabasesExceptLocal 1
2017-12-03T21:00:53.515+0900 I REPL     [replication-0] ******
2017-12-03T21:00:53.515+0900 I REPL     [replication-0] creating replication oplog of size: 6116MB...
2017-12-03T21:00:53.534+0900 I STORAGE  [replication-0] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-12-03T21:00:53.534+0900 I STORAGE  [replication-0] The size storer reports that the oplog contains 0 records totaling to 0 bytes
2017-12-03T21:00:53.534+0900 I STORAGE  [replication-0] Scanning the oplog to determine where to place markers for truncation
2017-12-03T21:00:53.634+0900 I REPL     [replication-0] ******
2017-12-03T21:00:53.635+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:00:53.637+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (1 connections now open to localhost:47017)
2017-12-03T21:00:53.639+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:00:53.641+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (2 connections now open to localhost:47017)
2017-12-03T21:00:53.645+0900 I REPL     [replication-1] No need to apply operations. (currently at { : Timestamp 1512302451000|1 })
2017-12-03T21:00:53.646+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:47017 due to bad connection status; 1 connections to that host remain open
2017-12-03T21:00:53.646+0900 I REPL     [replication-1] Finished fetching oplog during initial sync: CallbackCanceled: Callback canceled. Last fetched optime and hash: { ts: Timestamp 1512302451000|1, t: -1 }[2865188406503243212]
2017-12-03T21:00:53.647+0900 I REPL     [replication-1] Initial sync attempt finishing up.
2017-12-03T21:00:53.647+0900 I REPL     [replication-1] Initial Sync Attempt Statistics: { failedInitialSyncAttempts: 0, maxFailedInitialSyncAttempts: 10, initialSyncStart: new Date(1512302453478), initialSyncAttempts: [], fetchedMissingDocs: 0, appliedOps: 0, initialSyncOplogStart: Timestamp 1512302451000|1, initialSyncOplogEnd: Timestamp 1512302451000|1, databases: { databasesCloned: 0 } }
2017-12-03T21:00:53.654+0900 I REPL     [replication-1] initial sync done; took 0s.
2017-12-03T21:00:53.654+0900 I REPL     [replication-1] Starting replication fetcher thread
2017-12-03T21:00:53.654+0900 I REPL     [replication-1] Starting replication applier thread
2017-12-03T21:00:53.654+0900 I REPL     [replication-1] Starting replication reporter thread
2017-12-03T21:00:53.654+0900 I REPL     [rsSync] transition to RECOVERING
2017-12-03T21:00:53.655+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-03T21:00:53.656+0900 I REPL     [rsSync] transition to SECONDARY
2017-12-03T21:00:53.656+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state SECONDARY
2017-12-03T21:01:03.657+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state PRIMARY
2017-12-03T21:01:08.659+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47019
2017-12-03T21:01:08.659+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-03T21:01:08.661+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 2ms (1 connections now open to localhost:47019)
2017-12-03T21:01:08.662+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-03T21:01:08.663+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 1ms (2 connections now open to localhost:47019)
2017-12-03T21:02:10.737+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43882 #5 (3 connections now open)
2017-12-03T21:02:10.737+0900 I NETWORK  [conn5] received client metadata from 127.0.0.1:43882 conn5: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.832+0900 I INDEX    [repl writer worker 1] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2017-12-03T21:02:10.832+0900 I INDEX    [repl writer worker 1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-03T21:02:10.833+0900 I INDEX    [repl writer worker 1] build index done.  scanned 0 total records. 0 secs
2017-12-03T21:02:10.834+0900 I COMMAND  [repl writer worker 2] setting featureCompatibilityVersion to 3.4
2017-12-03T21:02:10.834+0900 I SHARDING [repl writer worker 7] initializing sharding state with: { _id: "shardIdentity", configsvrConnectionString: "csReplSet/localhost:57040,localhost:57041,localhost:57042", shardName: "s1", clusterId: ObjectId('5a23e786bf51d32cbcc946a4') }
2017-12-03T21:02:10.834+0900 I SHARDING [repl writer worker 7] first cluster operation detected, adding sharding hook to enable versioning and authentication to remote servers
2017-12-03T21:02:10.835+0900 I NETWORK  [repl writer worker 7] Starting new replica set monitor for csReplSet/localhost:57040,localhost:57041,localhost:57042
2017-12-03T21:02:10.836+0900 I SHARDING [thread2] creating distributed lock ping thread for process kris-ThinkPad-X1-Carbon-5th:47018:1512302530:4272451777790352026 (sleeping for 30000ms)
2017-12-03T21:02:10.837+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-03T21:02:10.837+0900 I NETWORK  [shard registry reload] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-03T21:02:10.837+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.838+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-03T21:02:10.843+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.843+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 6ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.844+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 5ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.845+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s0/localhost:37017,localhost:37018,localhost:37019
2017-12-03T21:02:10.845+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s1/localhost:47017,localhost:47018,localhost:47019
2017-12-03T21:02:10.850+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: LockStateChangeFailed: findAndModify query predicate didn't match any lock document
2017-12-03T21:02:10.851+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43954 #6 (4 connections now open)
2017-12-03T21:02:10.851+0900 I NETWORK  [conn6] received client metadata from 127.0.0.1:43954 conn6: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.854+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-03T21:02:10.855+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37019 (1 connections now open to localhost:37019 with a 5 second timeout)
2017-12-03T21:02:10.856+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43958 #7 (5 connections now open)
2017-12-03T21:02:10.856+0900 I NETWORK  [conn7] received client metadata from 127.0.0.1:43958 conn7: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.856+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-03T21:02:10.880+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43964 #8 (6 connections now open)
2017-12-03T21:02:10.880+0900 I NETWORK  [conn8] received client metadata from 127.0.0.1:43964 conn8: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.880+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-03T21:02:10.881+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-03T21:02:10.881+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43970 #9 (7 connections now open)
2017-12-03T21:02:10.881+0900 I NETWORK  [conn9] received client metadata from 127.0.0.1:43970 conn9: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.881+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-03T21:02:10.930+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44024 #10 (8 connections now open)
2017-12-03T21:02:10.930+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44026 #11 (9 connections now open)
2017-12-03T21:02:10.930+0900 I NETWORK  [conn10] received client metadata from 127.0.0.1:44024 conn10: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.930+0900 I NETWORK  [conn11] received client metadata from 127.0.0.1:44026 conn11: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:11.015+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44048 #12 (10 connections now open)
2017-12-03T21:02:11.015+0900 I NETWORK  [conn12] received client metadata from 127.0.0.1:44048 conn12: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:11.202+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44064 #13 (11 connections now open)
2017-12-03T21:02:11.202+0900 I NETWORK  [conn13] received client metadata from 127.0.0.1:44064 conn13: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.452+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44096 #14 (12 connections now open)
2017-12-03T21:02:27.453+0900 I NETWORK  [conn14] received client metadata from 127.0.0.1:44096 conn14: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.609+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44114 #15 (13 connections now open)
2017-12-03T21:02:27.609+0900 I NETWORK  [conn15] received client metadata from 127.0.0.1:44114 conn15: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.676+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44140 #16 (14 connections now open)
2017-12-03T21:02:40.677+0900 I NETWORK  [conn16] received client metadata from 127.0.0.1:44140 conn16: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.679+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44146 #17 (15 connections now open)
2017-12-03T21:02:40.680+0900 I NETWORK  [conn17] received client metadata from 127.0.0.1:44146 conn17: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.845+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:02:40.847+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-03T21:02:40.848+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s2/localhost:57017,localhost:57018,localhost:57019
2017-12-03T21:02:40.849+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-03T21:02:40.852+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-03T21:02:40.855+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57019 (1 connections now open to localhost:57019 with a 5 second timeout)
2017-12-03T21:03:10.845+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Ending idle connection to host localhost:57040 because the pool meets constraints; 1 connections to that host remain open
2017-12-03T21:03:10.848+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:03:10.850+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T21:09:40.866+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:09:40.867+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T21:55:10.958+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:55:10.960+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T22:03:40.979+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T22:03:40.982+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 3ms (1 connections now open to localhost:57041)
2017-12-03T22:41:11.077+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T22:41:11.078+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T23:17:41.152+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T23:17:41.154+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-03T23:32:11.188+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T23:32:11.190+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T00:06:41.267+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T00:06:41.268+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T00:25:41.311+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T00:25:41.313+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T00:30:11.323+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T00:30:11.324+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T00:42:41.356+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T00:42:41.358+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T00:53:11.383+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T00:53:11.384+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T01:03:09.904+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-04T01:03:09.906+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 2ms (3 connections now open to localhost:47019)
2017-12-04T01:04:09.905+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47019 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T01:25:41.467+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T01:25:41.469+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T01:46:41.520+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T01:46:41.524+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 4ms (1 connections now open to localhost:57042)
2017-12-04T01:59:11.555+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T01:59:11.556+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T02:04:41.568+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T02:04:41.570+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T02:20:11.606+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T02:20:11.607+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T02:35:11.644+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T02:35:11.646+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T03:10:11.733+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T03:10:11.734+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T04:23:41.920+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T04:23:41.922+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T04:40:11.962+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T04:40:11.964+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T05:21:12.078+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T05:21:12.080+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T05:56:42.169+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T05:56:42.171+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T06:51:42.314+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T06:51:42.315+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T07:26:12.406+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T07:26:12.408+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T07:28:42.413+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T07:28:42.415+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T15:41:54.169+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47019 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:41:54.176+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:47019 due to bad connection status; 0 connections to that host remain open
2017-12-04T15:41:54.185+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-04T15:41:54.180+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-04T15:41:54.180+0900 I REPL     [replication-2] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 126641 -- target:localhost:47019 db:local expDate:2017-12-04T08:14:55.761+0900 cmd:{ getMore: 34604852486, collection: "oplog.rs", maxTimeMS: 5000, term: 1, lastKnownCommittedOpTime: { ts: Timestamp 1512342825000|1, t: 1 } }. Last fetched optime (with hash): { ts: Timestamp 1512342825000|1, t: 1 }[5334871594228210341]. Restarts remaining: 3
2017-12-04T15:41:54.185+0900 I REPL     [replication-2] Scheduled new oplog query Fetcher source: localhost:47019 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512342825000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1, readConcern: { afterOpTime: { ts: Timestamp 1512342825000|1, t: 1 } } } query metadata: { $replData: 1, $oplogQueryData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 126658 -- target:localhost:47019 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512342825000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1, readConcern: { afterOpTime: { ts: Timestamp 1512342825000|1, t: 1 } } } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
2017-12-04T15:41:54.185+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-04T15:41:54.185+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-04T15:41:54.187+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47017
2017-12-04T15:41:54.187+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47019
2017-12-04T15:41:54.197+0900 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received a yes vote from localhost:47019; response message: { term: 1, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T15:41:54.197+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-04T15:41:54.202+0900 I REPL     [ReplicationExecutor] VoteRequester(term 2) received a no vote from localhost:47019 with reason "already voted for another candidate this term"; response message: { term: 2, voteGranted: false, reason: "already voted for another candidate this term", ok: 1.0 }
2017-12-04T15:41:54.205+0900 I REPL     [ReplicationExecutor] VoteRequester(term 2) received a no vote from localhost:47017 with reason "candidate's data is staler than mine"; response message: { term: 2, voteGranted: false, reason: "candidate's data is staler than mine", ok: 1.0 }
2017-12-04T15:41:54.205+0900 I REPL     [ReplicationExecutor] not becoming primary, we received insufficient votes
2017-12-04T15:41:54.210+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 25ms (2 connections now open to localhost:47019)
2017-12-04T15:41:54.210+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 25ms (2 connections now open to localhost:47019)
2017-12-04T15:41:54.212+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57040 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T15:41:54.212+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T15:41:54.212+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47019, took 26ms (2 connections now open to localhost:47019)
2017-12-04T15:41:54.212+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47017, took 26ms (2 connections now open to localhost:47017)
2017-12-04T15:41:54.212+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: Sync source's last applied OpTime { ts: Timestamp 1512342825000|1, t: 1 } is not greater than our last fetched OpTime { ts: Timestamp 1512342825000|1, t: 1 }. Choosing new sync source.
2017-12-04T15:41:54.212+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47017
2017-12-04T15:41:54.213+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T15:41:54.217+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 5ms (1 connections now open to localhost:47017)
2017-12-04T15:41:54.240+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47019: InvalidSyncSource: Sync source changed from localhost:47019 to localhost:47017
2017-12-04T15:41:54.242+0900 I REPL     [replication-0] Choosing new sync source because our current sync source, localhost:47017, has an OpTime ({ ts: Timestamp 1512369714000|1, t: 1 }) which is not ahead of ours ({ ts: Timestamp 1512369714000|1, t: 1 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-04T15:41:54.242+0900 I REPL     [replication-0] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:47017, OpTime { ts: Timestamp 1512369714000|1, t: 1 }, its sync source index:-1
2017-12-04T15:41:54.242+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:47017 (config version: 1; last applied optime: { ts: Timestamp 1512369714000|1, t: 1 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-04T15:41:54.242+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-04T15:41:54.242+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state SECONDARY
2017-12-04T15:41:54.250+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47017: InvalidSyncSource: Sync source was cleared. Was localhost:47017
2017-12-04T15:42:04.639+0900 I -        [conn4] end connection 127.0.0.1:43708 (15 connections now open)
2017-12-04T15:42:04.640+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:48070 #18 (15 connections now open)
2017-12-04T15:42:04.641+0900 I NETWORK  [conn18] received client metadata from 127.0.0.1:48070 conn18: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:42:09.243+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state PRIMARY
2017-12-04T15:42:09.245+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47019
2017-12-04T15:42:10.465+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T15:42:10.466+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T15:42:10.837+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:57017)
2017-12-04T15:42:10.839+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-04T15:42:10.840+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:57040)
2017-12-04T15:42:10.842+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-04T15:42:10.844+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:37017)
2017-12-04T15:42:10.845+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-04T15:42:10.847+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:47017)
2017-12-04T15:42:10.848+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-04T15:42:24.213+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T15:42:24.216+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 4ms (1 connections now open to localhost:57041)
2017-12-04T15:42:54.202+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:47019 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:42:54.205+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:57:11.239+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T15:57:11.243+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-04T16:12:11.267+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T16:12:11.269+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T16:45:25.216+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state SECONDARY
2017-12-04T16:45:25.268+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57041 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T16:45:25.268+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T16:45:30.218+0900 I REPL     [replication-0] Choosing new sync source because our current sync source, localhost:47019, has an OpTime ({ ts: Timestamp 1512372452000|1, t: 3 }) which is not ahead of ours ({ ts: Timestamp 1512372452000|1, t: 3 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-04T16:45:30.218+0900 I REPL     [replication-0] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:47019, OpTime { ts: Timestamp 1512372452000|1, t: 3 }, its sync source index:-1
2017-12-04T16:45:30.218+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:47019 (config version: 1; last applied optime: { ts: Timestamp 1512372452000|1, t: 3 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-04T16:45:30.218+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-04T16:45:30.219+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47019: InvalidSyncSource: Sync source was cleared. Was localhost:47019
2017-12-04T16:45:31.892+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T16:45:31.894+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T16:45:32.303+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:57019)
2017-12-04T16:45:32.305+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57019 (1 connections now open to localhost:57019 with a 5 second timeout)
2017-12-04T16:45:32.306+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:57041)
2017-12-04T16:45:32.308+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-04T16:45:32.309+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:37018)
2017-12-04T16:45:32.310+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-04T16:45:32.311+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:47019)
2017-12-04T16:45:32.313+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-04T16:45:32.314+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s1
2017-12-04T16:45:35.790+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-04T16:45:35.790+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-04T16:45:35.791+0900 I REPL     [ReplicationExecutor] VoteRequester(term 3 dry run) received a yes vote from localhost:47017; response message: { term: 3, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T16:45:35.791+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-04T16:45:35.797+0900 I REPL     [ReplicationExecutor] VoteRequester(term 4) received a yes vote from localhost:47017; response message: { term: 4, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T16:45:35.797+0900 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 4
2017-12-04T16:45:35.797+0900 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-12-04T16:45:35.797+0900 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-12-04T16:45:35.797+0900 I REPL     [ReplicationExecutor] Caught up to the latest optime known via heartbeats after becoming primary.
2017-12-04T16:45:35.798+0900 I REPL     [ReplicationExecutor] Exited primary catch-up mode.
2017-12-04T16:45:37.218+0900 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-12-04T16:45:40.194+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37890 #19 (16 connections now open)
2017-12-04T16:45:40.195+0900 I NETWORK  [conn19] received client metadata from 127.0.0.1:37890 conn19: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:40.197+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37892 #20 (17 connections now open)
2017-12-04T16:45:40.197+0900 I NETWORK  [conn20] received client metadata from 127.0.0.1:37892 conn20: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:40.256+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37894 #21 (18 connections now open)
2017-12-04T16:45:40.256+0900 I NETWORK  [conn21] received client metadata from 127.0.0.1:37894 conn21: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:40.258+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37896 #22 (19 connections now open)
2017-12-04T16:45:40.259+0900 I NETWORK  [conn22] received client metadata from 127.0.0.1:37896 conn22: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:51.230+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38014 #23 (20 connections now open)
2017-12-04T16:45:51.231+0900 I NETWORK  [conn23] received client metadata from 127.0.0.1:38014 conn23: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:46:25.219+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47019 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T16:46:31.897+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T16:46:31.897+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 0ms (1 connections now open to localhost:57040)
2017-12-04T17:01:31.931+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T17:01:31.933+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T17:38:04.887+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:36404 #24 (21 connections now open)
2017-12-04T17:38:04.888+0900 I NETWORK  [conn24] received client metadata from 127.0.0.1:36404 conn24: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:38:04.905+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:36406 #25 (22 connections now open)
2017-12-04T17:38:04.905+0900 I NETWORK  [conn25] received client metadata from 127.0.0.1:36406 conn25: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-3", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:38:11.971+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:36468 #26 (23 connections now open)
2017-12-04T17:38:11.972+0900 I NETWORK  [conn26] received client metadata from 127.0.0.1:36468 conn26: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-0", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:38:42.279+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:36718 #27 (24 connections now open)
2017-12-04T17:38:42.280+0900 I NETWORK  [conn27] received client metadata from 127.0.0.1:36718 conn27: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:39:32.672+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37120 #28 (25 connections now open)
2017-12-04T17:39:32.672+0900 I NETWORK  [conn28] received client metadata from 127.0.0.1:37120 conn28: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:44:53.964+0900 I -        [conn26] end connection 127.0.0.1:36468 (25 connections now open)
2017-12-04T17:45:13.889+0900 I -        [conn27] end connection 127.0.0.1:36718 (24 connections now open)
2017-12-04T17:45:20.409+0900 I -        [conn28] end connection 127.0.0.1:37120 (23 connections now open)
2017-12-04T17:45:23.469+0900 I -        [conn25] end connection 127.0.0.1:36406 (22 connections now open)
2017-12-04T17:50:04.167+0900 I INDEX    [conn24] build index on: mongomart.item properties: { v: 2, key: { _fts: "text", _ftsx: 1 }, name: "title_text_slogan_text_description_text", ns: "mongomart.item", weights: { description: 1, slogan: 1, title: 1 }, default_language: "english", language_override: "language", textIndexVersion: 3 }
2017-12-04T17:50:04.168+0900 I INDEX    [conn24] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-04T17:50:04.177+0900 I INDEX    [conn24] build index done.  scanned 23 total records. 0 secs
2017-12-04T17:50:40.646+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42600 #29 (22 connections now open)
2017-12-04T17:50:40.646+0900 I NETWORK  [conn29] received client metadata from 127.0.0.1:42600 conn29: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-0", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:50:44.595+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42636 #30 (23 connections now open)
2017-12-04T17:50:44.595+0900 I NETWORK  [conn30] received client metadata from 127.0.0.1:42636 conn30: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:50:57.819+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42742 #31 (24 connections now open)
2017-12-04T17:50:57.820+0900 I NETWORK  [conn31] received client metadata from 127.0.0.1:42742 conn31: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:51:42.106+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43096 #32 (25 connections now open)
2017-12-04T17:51:42.106+0900 I NETWORK  [conn32] received client metadata from 127.0.0.1:43096 conn32: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-3", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:58:00.280+0900 I -        [conn30] end connection 127.0.0.1:42636 (25 connections now open)
2017-12-04T17:58:50.698+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:46612 #33 (25 connections now open)
2017-12-04T17:58:50.698+0900 I NETWORK  [conn33] received client metadata from 127.0.0.1:46612 conn33: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:02:33.071+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T18:02:33.072+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T18:03:45.708+0900 I -        [conn29] end connection 127.0.0.1:42600 (25 connections now open)
2017-12-04T18:03:50.699+0900 I -        [conn33] end connection 127.0.0.1:46612 (24 connections now open)
2017-12-04T18:04:20.686+0900 I -        [conn31] end connection 127.0.0.1:42742 (23 connections now open)
2017-12-04T18:04:29.801+0900 I -        [conn32] end connection 127.0.0.1:43096 (22 connections now open)
2017-12-04T18:05:02.174+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:49616 #34 (22 connections now open)
2017-12-04T18:05:02.174+0900 I NETWORK  [conn34] received client metadata from 127.0.0.1:49616 conn34: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-0", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:05:26.692+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:49810 #35 (23 connections now open)
2017-12-04T18:05:26.692+0900 I NETWORK  [conn35] received client metadata from 127.0.0.1:49810 conn35: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:06:12.899+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:50186 #36 (24 connections now open)
2017-12-04T18:06:12.900+0900 I NETWORK  [conn36] received client metadata from 127.0.0.1:50186 conn36: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:07:33.605+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:50860 #37 (25 connections now open)
2017-12-04T18:07:33.606+0900 I NETWORK  [conn37] received client metadata from 127.0.0.1:50860 conn37: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-3", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:11:12.902+0900 I -        [conn36] end connection 127.0.0.1:50186 (25 connections now open)
2017-12-04T18:12:28.823+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:53290 #38 (25 connections now open)
2017-12-04T18:12:28.823+0900 I NETWORK  [conn38] received client metadata from 127.0.0.1:53290 conn38: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:12:41.227+0900 I -        [conn35] end connection 127.0.0.1:49810 (25 connections now open)
2017-12-04T18:16:03.403+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:55086 #39 (25 connections now open)
2017-12-04T18:16:03.403+0900 I NETWORK  [conn39] received client metadata from 127.0.0.1:55086 conn39: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:27:35.272+0900 I -        [conn34] end connection 127.0.0.1:49616 (25 connections now open)
2017-12-04T18:27:50.878+0900 I -        [conn39] end connection 127.0.0.1:55086 (24 connections now open)
2017-12-04T18:27:57.952+0900 I -        [conn38] end connection 127.0.0.1:53290 (23 connections now open)
2017-12-04T18:28:04.414+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60928 #40 (23 connections now open)
2017-12-04T18:28:04.415+0900 I NETWORK  [conn40] received client metadata from 127.0.0.1:60928 conn40: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-0", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:28:04.433+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60930 #41 (24 connections now open)
2017-12-04T18:28:04.434+0900 I NETWORK  [conn41] received client metadata from 127.0.0.1:60930 conn41: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:28:13.294+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32776 #42 (25 connections now open)
2017-12-04T18:28:13.295+0900 I NETWORK  [conn42] received client metadata from 127.0.0.1:32776 conn42: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:28:13.307+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32778 #43 (26 connections now open)
2017-12-04T18:28:13.307+0900 I NETWORK  [conn43] received client metadata from 127.0.0.1:32778 conn43: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
