2017-12-03T21:00:51.826+0900 I CONTROL  [initandlisten] MongoDB starting : pid=9825 port=57019 dbpath=/data/shard2/rs2 64-bit host=kris-ThinkPad-X1-Carbon-5th
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] db version v3.4.10
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] modules: none
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] build environment:
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten]     distmod: ubuntu1604
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] options: { net: { port: 57019 }, processManagement: { fork: true }, replication: { replSet: "s2" }, sharding: { clusterRole: "shardsvr" }, storage: { dbPath: "/data/shard2/rs2" }, systemLog: { destination: "file", path: "s2-r2.log" } }
2017-12-03T21:00:51.848+0900 I STORAGE  [initandlisten] 
2017-12-03T21:00:51.848+0900 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-12-03T21:00:51.848+0900 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-12-03T21:00:51.848+0900 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7269M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:51.927+0900 W SHARDING [initandlisten] Started with --shardsvr, but no shardIdentity document was found on disk in admin.system.version. This most likely means this server has not yet been added to a sharded cluster.
2017-12-03T21:00:51.948+0900 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/shard2/rs2/diagnostic.data'
2017-12-03T21:00:51.972+0900 I REPL     [initandlisten] Did not find local voted for document at startup.
2017-12-03T21:00:51.972+0900 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2017-12-03T21:00:51.972+0900 I NETWORK  [thread1] waiting for connections on port 57019
2017-12-03T21:00:57.026+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51750 #1 (1 connection now open)
2017-12-03T21:00:57.026+0900 I -        [conn1] end connection 127.0.0.1:51750 (1 connection now open)
2017-12-03T21:00:57.027+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51754 #2 (1 connection now open)
2017-12-03T21:00:57.027+0900 I NETWORK  [conn2] received client metadata from 127.0.0.1:51754 conn2: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:57.027+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57017
2017-12-03T21:00:57.028+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57017, took 1ms (1 connections now open to localhost:57017)
2017-12-03T21:00:59.030+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51794 #3 (2 connections now open)
2017-12-03T21:00:59.031+0900 I -        [conn3] end connection 127.0.0.1:51794 (2 connections now open)
2017-12-03T21:00:59.072+0900 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-12-03T21:00:59.137+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51796 #4 (2 connections now open)
2017-12-03T21:00:59.137+0900 I NETWORK  [conn4] received client metadata from 127.0.0.1:51796 conn4: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:59.138+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57018
2017-12-03T21:00:59.139+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57018, took 1ms (1 connections now open to localhost:57018)
2017-12-03T21:00:59.142+0900 I REPL     [ReplicationExecutor] New replica set config in use: { _id: "s2", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "localhost:57017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "localhost:57018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "localhost:57019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a23e77974cc47503351a376') } }
2017-12-03T21:00:59.142+0900 I REPL     [ReplicationExecutor] This node is localhost:57019 in the config
2017-12-03T21:00:59.142+0900 I REPL     [ReplicationExecutor] transition to STARTUP2
2017-12-03T21:00:59.143+0900 I REPL     [replication-0] Starting initial sync (attempt 1 of 10)
2017-12-03T21:00:59.143+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state SECONDARY
2017-12-03T21:00:59.143+0900 I REPL     [ReplicationExecutor] Member localhost:57018 is now in state STARTUP2
2017-12-03T21:00:59.178+0900 I REPL     [replication-0] sync source candidate: localhost:57017
2017-12-03T21:00:59.178+0900 I STORAGE  [replication-0] dropAllDatabasesExceptLocal 1
2017-12-03T21:00:59.178+0900 I REPL     [replication-0] ******
2017-12-03T21:00:59.178+0900 I REPL     [replication-0] creating replication oplog of size: 6071MB...
2017-12-03T21:00:59.196+0900 I STORAGE  [replication-0] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-12-03T21:00:59.196+0900 I STORAGE  [replication-0] The size storer reports that the oplog contains 0 records totaling to 0 bytes
2017-12-03T21:00:59.196+0900 I STORAGE  [replication-0] Scanning the oplog to determine where to place markers for truncation
2017-12-03T21:00:59.273+0900 I REPL     [replication-0] ******
2017-12-03T21:00:59.274+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T21:00:59.276+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (1 connections now open to localhost:57017)
2017-12-03T21:00:59.277+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T21:00:59.279+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (2 connections now open to localhost:57017)
2017-12-03T21:00:59.280+0900 I REPL     [replication-1] No need to apply operations. (currently at { : Timestamp 1512302457000|1 })
2017-12-03T21:00:59.281+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:57017 due to bad connection status; 1 connections to that host remain open
2017-12-03T21:00:59.282+0900 I REPL     [replication-1] Finished fetching oplog during initial sync: CallbackCanceled: Callback canceled. Last fetched optime and hash: { ts: Timestamp 1512302457000|1, t: -1 }[3144501803686678102]
2017-12-03T21:00:59.282+0900 I REPL     [replication-1] Initial sync attempt finishing up.
2017-12-03T21:00:59.282+0900 I REPL     [replication-1] Initial Sync Attempt Statistics: { failedInitialSyncAttempts: 0, maxFailedInitialSyncAttempts: 10, initialSyncStart: new Date(1512302459142), initialSyncAttempts: [], fetchedMissingDocs: 0, appliedOps: 0, initialSyncOplogStart: Timestamp 1512302457000|1, initialSyncOplogEnd: Timestamp 1512302457000|1, databases: { databasesCloned: 0 } }
2017-12-03T21:00:59.292+0900 I REPL     [replication-1] initial sync done; took 0s.
2017-12-03T21:00:59.292+0900 I REPL     [replication-1] Starting replication fetcher thread
2017-12-03T21:00:59.293+0900 I REPL     [replication-1] Starting replication applier thread
2017-12-03T21:00:59.293+0900 I REPL     [replication-1] Starting replication reporter thread
2017-12-03T21:00:59.293+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-03T21:00:59.293+0900 I REPL     [rsSync] transition to RECOVERING
2017-12-03T21:00:59.294+0900 I REPL     [ReplicationExecutor] Member localhost:57018 is now in state SECONDARY
2017-12-03T21:00:59.294+0900 I REPL     [rsSync] transition to SECONDARY
2017-12-03T21:01:09.296+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state PRIMARY
2017-12-03T21:01:10.296+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:57017
2017-12-03T21:01:10.299+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T21:01:10.299+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 0ms (2 connections now open to localhost:57017)
2017-12-03T21:02:10.834+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51958 #5 (3 connections now open)
2017-12-03T21:02:10.834+0900 I NETWORK  [conn5] received client metadata from 127.0.0.1:51958 conn5: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.913+0900 I INDEX    [repl writer worker 1] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2017-12-03T21:02:10.913+0900 I INDEX    [repl writer worker 1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-03T21:02:10.914+0900 I INDEX    [repl writer worker 1] build index done.  scanned 0 total records. 0 secs
2017-12-03T21:02:10.915+0900 I COMMAND  [repl writer worker 3] setting featureCompatibilityVersion to 3.4
2017-12-03T21:02:10.922+0900 I SHARDING [repl writer worker 10] initializing sharding state with: { _id: "shardIdentity", configsvrConnectionString: "csReplSet/localhost:57040,localhost:57041,localhost:57042", shardName: "s2", clusterId: ObjectId('5a23e786bf51d32cbcc946a4') }
2017-12-03T21:02:10.922+0900 I SHARDING [repl writer worker 10] first cluster operation detected, adding sharding hook to enable versioning and authentication to remote servers
2017-12-03T21:02:10.923+0900 I NETWORK  [repl writer worker 10] Starting new replica set monitor for csReplSet/localhost:57040,localhost:57041,localhost:57042
2017-12-03T21:02:10.923+0900 I SHARDING [thread2] creating distributed lock ping thread for process kris-ThinkPad-X1-Carbon-5th:57019:1512302530:-5824242036816374222 (sleeping for 30000ms)
2017-12-03T21:02:10.924+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-03T21:02:10.924+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-03T21:02:10.924+0900 I NETWORK  [shard registry reload] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-03T21:02:10.926+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.926+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.927+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.927+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.927+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s0/localhost:37017,localhost:37018,localhost:37019
2017-12-03T21:02:10.927+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s1/localhost:47017,localhost:47018,localhost:47019
2017-12-03T21:02:10.939+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: LockStateChangeFailed: findAndModify query predicate didn't match any lock document
2017-12-03T21:02:10.947+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-03T21:02:10.951+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52060 #6 (4 connections now open)
2017-12-03T21:02:10.951+0900 I NETWORK  [conn6] received client metadata from 127.0.0.1:52060 conn6: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.977+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37019 (1 connections now open to localhost:37019 with a 5 second timeout)
2017-12-03T21:02:10.991+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-03T21:02:10.992+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-03T21:02:10.992+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-03T21:02:11.017+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-03T21:02:11.206+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52098 #7 (5 connections now open)
2017-12-03T21:02:11.206+0900 I NETWORK  [conn7] received client metadata from 127.0.0.1:52098 conn7: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.453+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52122 #8 (6 connections now open)
2017-12-03T21:02:27.453+0900 I NETWORK  [conn8] received client metadata from 127.0.0.1:52122 conn8: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.609+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52140 #9 (7 connections now open)
2017-12-03T21:02:27.610+0900 I NETWORK  [conn9] received client metadata from 127.0.0.1:52140 conn9: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.684+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52180 #10 (8 connections now open)
2017-12-03T21:02:40.684+0900 I NETWORK  [conn10] received client metadata from 127.0.0.1:52180 conn10: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.685+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52184 #11 (9 connections now open)
2017-12-03T21:02:40.686+0900 I NETWORK  [conn11] received client metadata from 127.0.0.1:52184 conn11: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.829+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52192 #12 (10 connections now open)
2017-12-03T21:02:40.830+0900 I NETWORK  [conn12] received client metadata from 127.0.0.1:52192 conn12: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.834+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52198 #13 (11 connections now open)
2017-12-03T21:02:40.835+0900 I NETWORK  [conn13] received client metadata from 127.0.0.1:52198 conn13: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.854+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52206 #14 (12 connections now open)
2017-12-03T21:02:40.854+0900 I NETWORK  [conn14] received client metadata from 127.0.0.1:52206 conn14: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.928+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:02:40.929+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T21:02:40.930+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s2/localhost:57017,localhost:57018,localhost:57019
2017-12-03T21:02:40.932+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-03T21:02:40.933+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52226 #15 (13 connections now open)
2017-12-03T21:02:40.934+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-03T21:02:40.934+0900 I NETWORK  [conn15] received client metadata from 127.0.0.1:52226 conn15: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.935+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52228 #16 (14 connections now open)
2017-12-03T21:02:40.935+0900 I NETWORK  [conn16] received client metadata from 127.0.0.1:52228 conn16: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.936+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57019 (1 connections now open to localhost:57019 with a 5 second timeout)
2017-12-03T21:02:40.939+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52232 #17 (15 connections now open)
2017-12-03T21:02:40.940+0900 I NETWORK  [conn17] received client metadata from 127.0.0.1:52232 conn17: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:03:10.927+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Ending idle connection to host localhost:57040 because the pool meets constraints; 1 connections to that host remain open
2017-12-03T21:03:10.930+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:03:10.931+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-03T21:53:41.053+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:53:41.054+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T22:12:41.088+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T22:12:41.089+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T22:17:41.097+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T22:17:41.098+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T22:27:41.125+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T22:27:41.127+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-03T22:51:44.320+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T22:51:44.322+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-03T22:52:44.321+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T23:09:11.221+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T23:09:11.223+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T23:18:41.245+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T23:18:41.248+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 3ms (1 connections now open to localhost:57041)
2017-12-03T23:27:34.389+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T23:27:34.391+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-03T23:28:34.390+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T23:29:11.271+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T23:29:11.272+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-03T23:44:41.305+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T23:44:41.307+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T00:17:41.393+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T00:17:41.395+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T01:15:09.590+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T01:15:09.591+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-04T01:16:09.591+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T01:47:11.611+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T01:47:11.615+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 4ms (1 connections now open to localhost:57041)
2017-12-04T01:54:41.630+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T01:54:41.632+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T02:10:11.671+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T02:10:11.672+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T02:24:41.707+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T02:24:41.708+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T02:43:41.752+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T02:43:41.754+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T03:59:41.939+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T03:59:41.941+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T04:03:14.919+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T04:03:14.921+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-04T04:04:14.920+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T04:07:11.959+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T04:07:11.961+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T04:23:11.999+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T04:23:12.011+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 12ms (1 connections now open to localhost:57041)
2017-12-04T04:37:12.046+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T04:37:12.047+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T05:45:42.216+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T05:45:42.217+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T06:25:05.217+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T06:25:05.219+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 3ms (3 connections now open to localhost:57017)
2017-12-04T06:26:05.217+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T06:31:42.345+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T06:31:42.347+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T07:44:12.528+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T07:44:12.530+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T15:41:54.182+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:41:54.191+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:57017 due to bad connection status; 0 connections to that host remain open
2017-12-04T15:41:54.191+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T15:41:54.185+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-04T15:41:54.191+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-04T15:41:54.191+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57017
2017-12-04T15:41:54.191+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57018
2017-12-04T15:41:54.191+0900 I REPL     [replication-0] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 134604 -- target:localhost:57017 db:local expDate:2017-12-04T08:14:55.440+0900 cmd:{ getMore: 21465883049, collection: "oplog.rs", maxTimeMS: 5000, term: 1, lastKnownCommittedOpTime: { ts: Timestamp 1512342830000|1, t: 1 } }. Last fetched optime (with hash): { ts: Timestamp 1512342830000|1, t: 1 }[2855280599495995645]. Restarts remaining: 3
2017-12-04T15:41:54.192+0900 I REPL     [replication-0] Scheduled new oplog query Fetcher source: localhost:57017 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512342830000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1, readConcern: { afterOpTime: { ts: Timestamp 1512342830000|1, t: 1 } } } query metadata: { $replData: 1, $oplogQueryData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 134623 -- target:localhost:57017 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512342830000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1, readConcern: { afterOpTime: { ts: Timestamp 1512342830000|1, t: 1 } } } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
2017-12-04T15:41:54.192+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T15:41:54.195+0900 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received a yes vote from localhost:57018; response message: { term: 1, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T15:41:54.195+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-04T15:41:54.199+0900 I REPL     [ReplicationExecutor] VoteRequester(term 2) received a no vote from localhost:57017 with reason "candidate's data is staler than mine"; response message: { term: 2, voteGranted: false, reason: "candidate's data is staler than mine", ok: 1.0 }
2017-12-04T15:41:54.200+0900 I REPL     [ReplicationExecutor] VoteRequester(term 2) received a yes vote from localhost:57018; response message: { term: 2, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T15:41:54.201+0900 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 2
2017-12-04T15:41:54.201+0900 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-12-04T15:41:54.201+0900 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-12-04T15:41:54.201+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state SECONDARY
2017-12-04T15:41:54.201+0900 I REPL     [ReplicationExecutor] Heartbeats updated catchup target optime to { ts: Timestamp 1512369714000|1, t: 1 }
2017-12-04T15:41:54.212+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57018, took 21ms (2 connections now open to localhost:57018)
2017-12-04T15:41:54.212+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57040 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T15:41:54.212+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T15:41:54.214+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 22ms (2 connections now open to localhost:57017)
2017-12-04T15:41:54.214+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 23ms (2 connections now open to localhost:57017)
2017-12-04T15:41:54.221+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57017, took 30ms (2 connections now open to localhost:57017)
2017-12-04T15:41:54.230+0900 I REPL     [rsSync] Caught up to the latest known optime successfully after becoming primary.
2017-12-04T15:41:54.230+0900 I REPL     [rsSync] Exited primary catch-up mode.
2017-12-04T15:41:54.233+0900 I REPL     [rsBackgroundSync] Replication producer stopped after oplog fetcher finished returning a batch from our sync source.  Abandoning this batch of oplog entries and re-evaluating our sync source.
2017-12-04T15:41:55.231+0900 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-12-04T15:41:57.183+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:56062 #18 (16 connections now open)
2017-12-04T15:41:57.183+0900 I NETWORK  [conn18] received client metadata from 127.0.0.1:56062 conn18: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:41:57.186+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:56064 #19 (17 connections now open)
2017-12-04T15:41:57.187+0900 I NETWORK  [conn19] received client metadata from 127.0.0.1:56064 conn19: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:41:59.227+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:57017: InvalidSyncSource: Sync source was cleared. Was localhost:57017
2017-12-04T15:41:59.232+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:56090 #20 (18 connections now open)
2017-12-04T15:41:59.232+0900 I NETWORK  [conn20] received client metadata from 127.0.0.1:56090 conn20: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:41:59.233+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:56092 #21 (19 connections now open)
2017-12-04T15:41:59.233+0900 I NETWORK  [conn21] received client metadata from 127.0.0.1:56092 conn21: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:42:07.244+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:56102 #22 (20 connections now open)
2017-12-04T15:42:07.245+0900 I NETWORK  [conn22] received client metadata from 127.0.0.1:56102 conn22: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:42:10.544+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T15:42:10.546+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T15:42:10.871+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:57017)
2017-12-04T15:42:10.872+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-04T15:42:10.874+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:57040)
2017-12-04T15:42:10.875+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-04T15:42:10.876+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:37017)
2017-12-04T15:42:10.878+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-04T15:42:10.879+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:47017)
2017-12-04T15:42:10.880+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-04T15:42:54.201+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:42:54.201+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:42:54.227+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:44:40.551+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T15:44:40.553+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T15:58:30.263+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:59260 #23 (21 connections now open)
2017-12-04T15:58:30.266+0900 I NETWORK  [conn23] received client metadata from 127.0.0.1:59260 conn23: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:59:30.264+0900 I -        [conn18] end connection 127.0.0.1:56062 (21 connections now open)
